#' Constructor for the `EnsembleSample` class
#'
#' A constructor for the `EnsembleSample` class. This is a container for the samples or
#' and MLE point estimates generated by the Kalman filter
#'
#' @param ensemble_fit The `EnsembleFit` object containing the fitted ensemble model.
#' @param mle The MLE point estimate of the Kalman filter using the `ensemble_fit` object.
#' @param sample A sampling of the Kalman filter using the `ensemble_fit` object.
#' @return An object of type \linkS4class{EnsembleSample}
#' @export
EnsembleSample <- function(ensemble_fit, mle, sample) {
  ensemble_sample <- new('EnsembleSample',
                         ensemble_fit = ensemble_fit,
                         mle = mle,
                         sample = sample)
  return(ensemble_sample)
}

#### Class definition ####
#' A class to hold the samples of the ensemble model from the Kalman filter
#'
#'
#' `EnsembleSample` objects are generated using the `generate_sample` function.
#'
#' The `mle` and `sample` slots are \eqn{T \times (M + 2)\times N_{sample}} arrays where
#' \eqn{T} is the time the ensemble model was run for, \eqn{M} is the number of simulators
#' and \eqn{N_{sample}} is the number of samples from the Kalman filter. For each time step,
#' the \eqn{t}th element of the array \eqn{S[t, ,]} is a matrix where each column is a
#' sample and the rows are the variables:
#' \deqn{\left( y^{(t)}, \eta^{(t)}, z_1^{(t)}, z_2^{(t)} \ldots, z_M^{(t)}   \right)}
#' where \eqn{y^{(t)}} is the ensemble model's prediction of the latent truth value at time \eqn{t},
#' \eqn{\eta^{(t)}} is the shared short-term discrepancy at time \eqn{t},
#' \eqn{z_i^{(t)}} is the individual short-term discrepancy of simulator \eqn{i} at time \eqn{t}.
#'
#' Each sample in the `sample` slot is a sample from the Kalman filter, while each sample in
#' the `mle` slot is the MLE for the Kalman filter for every given sample of the ensemble model.
#'
#' @slot ensemble_fit The `EnsembleFit` object of the fitted ensemble model.
#' @slot mle The MLE point estimates for the Kalman filter.
#' @slot sample Sample from the Kalman filter.
#'
#' @export
setClass(
  "EnsembleSample",
  slots = c(
    ensemble_fit = "EnsembleFit",
    mle = "array",
    sample = "array"
  )
)
