#' Constructor for the `EnsembleFit` class
#'
#' A constructor for the `EnsembleFit` class. This is a container for the samples or
#' point estimates generated by the fitted Stan models.
#'
#' @param ensemble_data The `EnsembleData` object encapsulating the data initially passed
#' through to Stan when fitting the ensemble model.
#' @param samples The `stanfit` object representing the samples drawn from the Stan model.
#' @param point_estimate The `list` output of `rstan::optimizing` if a full sampling is
#' not completed.
#' @return An object of type \linkS4class{EnsembleFit}
#' @export
EnsembleFit <- function(ensemble_data, samples = NULL, point_estimate = NULL) {
  ensemble_data <- new('EnsembleFit',
                       ensemble_data = ensemble_data,
                       samples = samples,
                       point_estimate = point_estimate)
  return(ensemble_data)
}


setClassUnion("stanfit_or_null", c("stanfit", "NULL"))
setClassUnion("list_or_null", c("list", "NULL"))


#### Class definition ####
#' A class to hold the samples or point estimates from the ensemble model.
#'
#' An `EnsembleFit` object is returned by the `fit_ensemble_model` function.
#' The object contains a slot for the `EnsembleData` object originally used to
#' fit the ensemble model. The `samples` slot contains the samples from the MCMC
#' if a full sampling was completed, otherwise the `point_estimate` slot contains
#' information about a point estimate.
#'
#'
#' @slot ensemble_data The `EnsembleData` object encapsulating the data initially passed
#' through to Stan when fitting the ensemble model.
#' @slot samples The `stanfit` object representing the samples drawn from the Stan
#' model. This is `NULL` if only a point estimate is generated.
#' @slot point_estimate The `list` output of `rstan::optimizing` if a full sampling is
#' not completed. Otherwise, this is `NULL`.
#'
#' @export
setClass(
  "EnsembleFit",
  slots = c(
    ensemble_data = "EnsembleData",
    samples = "stanfit_or_null",
    point_estimate = "list_or_null"
  )
)
