# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Dummy
#' @description This is a dummy function.
#' @param input a numerical input
#' @details This is a dummy function.
#' @return Nothing.
#' @examples
#' AGFCEM(3.0)
#' @export
AGFCEM <- function(input) {
    invisible(.Call(`_EcoEnsemble_AGFCEM`, input))
}

